MODULES: targzs

targzs: packages/example-cmd-0.0.tar.gz

packages/example-cmd-0.0.tar.gz:
	mkdir -p packages
	cd .. && tar cfz Modules/packages/example-cmd-0.0.tar.gz Modules/example-cmd.ngm/0.0

.PHONY: MODULES packages
