name:           NGLess
version:        '1.3.0'
category:       Domain Specific Language
author:         Luis Pedro Coelho and others (see AUTHORS)
maintainer:     luis@luispedro.org
github:         ngless-toolkit/ngless
license:        MIT
license-file:   COPYING
c-sources:
  - NGLess/Dependencies/embedded.c
  - NGLess/Data/FastQ.c
default-extensions:
  - BangPatterns
  - OverloadedStrings
  - LambdaCase
  - TupleSections
other-extensions:
  - DeriveDataTypeable
  - TemplateHaskell
dependencies:
  - aeson >=0.9
  - ansi-terminal
  - async
  - atomic-write >=0.2
  - base
  - bytestring
  - bytestring-lexing
  - optparse-applicative
  - conduit >= 1.3
  - conduit-algorithms >=0.0.9.0
  - conduit-extra >=1.1.12
  - configurator
  - containers
  - convertible
  - data-default
  - deepseq >=1.3
  - directory
  - edit-distance >=0.2
  - either
  - errors >=2.1
  - extra >=1.4
  - exceptions
  - filemanip >=0.3.6
  - filepath >=1.3
  - file-embed >=0.0.8
  - gitrev
  - hashable
  - hashtables
  - hostname
  - http-conduit
  - http-client
  - inline-c
  - inline-c-cpp
  - int-interval-map
  - mtl >=2.2
  - MissingH >=1.3
  - network
  - parsec >=3.1
  - primitive >=0.6
  - process >=1.2.3
  - regex
  - safe
  - strict
  - stm
  - stm-chans
  - stm-conduit >=2.7
  - resourcet >=1.1
  - tar >=0.5
  - template-haskell
  - text >=1.2
  - time >=1.5
  - transformers
  - tar-conduit >= 0.3.2
  - unix-compat
  - unliftio-core
  - unliftio
  - vector >=0.11
  - vector-algorithms
  - yaml
  - zlib
  - diagrams-lib
  - diagrams-svg
  - diagrams-core

ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-tabs
  - -fno-warn-missing-signatures
  - -threaded
  - -O2
  - -fno-full-laziness
  - -rtsopts
  - ! '"-with-rtsopts=-A64m -n4m -H"'

when:
  - condition: ! 'os(windows)'
    then:
     cpp-options: -DWINDOWS
     dependencies:
     - atomic-write
    else:
     dependencies:
     - bzlib-conduit
     - double-conversion
     - safeio >=0.0.2
     - unix

executables:
  ngless:
    main: Main.hs
    source-dirs: Execs
    other-modules: []
    dependencies:
        - NGLess
    when:
    - condition: ! '!(flag(embed))'
      then:
        cc-options: -DNO_EMBED_SAMTOOLS_BWA
        cpp-options: -DNO_EMBED_SAMTOOLS_BWA
      else:
        ld-options:
        - -static
        - -pthread
library:
    source-dirs: NGLess/
    when:
    - condition: ! '!(flag(embed))'
      then:
        cc-options: -DNO_EMBED_SAMTOOLS_BWA
        cpp-options: -DNO_EMBED_SAMTOOLS_BWA
      else:
        ld-options:
        - -static
        - -pthread
tests:
  nglesstest:
    main: Tests.hs
    source-dirs:
        - NGLess
        - Tests-Src/
    cpp-options: -DIS_BUILDING_TEST
    dependencies:
    - HUnit >=1.3
    - test-framework >=0.8
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - QuickCheck >=2.8
    when:
    - condition: ! '!(flag(embed))'
      then:
        cc-options: -DNO_EMBED_SAMTOOLS_BWA
        cpp-options: -DNO_EMBED_SAMTOOLS_BWA
      else:
        ld-options:
        - -static
        - -pthread
benchmarks:
  nglessbench:
    main: Bench.hs
    source-dirs: Execs/
    other-modules: []
    cc-options: -DNO_EMBED_SAMTOOLS_BWA
    cpp-options: -DNO_EMBED_SAMTOOLS_BWA
    dependencies:
    - NGLess
    - HUnit >=1.3
    - criterion
flags:
  embed:
    description: Embed bwa/samtools
    manual: false
    default: false
