# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

resolver: lts-14.20
compiler-check: newer-minor

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - git: "https://github.com/ngless-toolkit/interval-to-int"
    commit: "78289f6b48d41f7cc48169520ec9b77b050a0029"


allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.10.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

