#!/usr/bin/env cwl-runner
# This tool description was initially generated by argparse2tool ver. 0.4.3-2
# and later modified by hand

cwlVersion: v1.0

class: CommandLineTool
baseCommand: ['ngless-select.py']

requirements:
- $import: ngl-types.yml

doc: |
  None

inputs:

  input:
    type: File
    doc: SAM/BAM/CRAM file filter
    inputBinding:
      prefix: --input

  output:
    type: string
    doc: Output file/path for results
    default: select-output.bam
    inputBinding:
      prefix: --output

  action:
    type: ngl-types.yml#keep_drop_action
    doc: Whether to keep or drop when condition are met
    doc: When selecting reads, target reads are either kept or dropped (see also 'Filter conditions')
    inputBinding:
      prefix: --action

  conditions:
    type: ngl-types.yml#filter_conditions[]
    doc: When keeping/dropping reads select which subset should be targetted
    inputBinding:
      prefix: --conditions

  debug:
    type: boolean?
    default: False
    doc: Prints the payload before submitting to ngless
    inputBinding:
      prefix: --debug

outputs:
  output_file:
    type: File
    outputBinding:
      glob: $(inputs.output)
