#!/usr/bin/env cwl-runner
# This tool description was initially generated by argparse2tool ver. 0.4.3-2
# and later modified by hand

cwlVersion: v1.0

class: CommandLineTool
baseCommand: ['ngless-select.py']

doc: |
  None

inputs:

  input:
    type: File
    doc: SAM/BAM/CRAM file filter
    inputBinding:
      prefix: --input

  output:
    type: string
    doc: Output file/path for results
    default: select-output.bam
    inputBinding:
      prefix: --output

  action:
    type:
      type: enum
      symbols: ['keep_if', 'drop_if']
    doc: Whether to keep or drop when condition are met
    inputBinding:
      prefix: --action

  conditions:
    type:
      type: enum
      symbols: ['mapped', 'unmapped', 'unique']
    doc: One or more conditions to filter on
    inputBinding:
      prefix: --conditions

  debug:
    type: boolean?
    default: False
    doc: Prints the payload before submitting to ngless
    inputBinding:
      prefix: --debug

outputs:
  output_file:
    type: File
    outputBinding:
      glob: $(inputs.output)
